"""15개 평가 항목의 개념·생활 예시·계산 순서·주의점을 관리하는 문서 원본."""

ITEMS = [
    {
        'id': 1, 'title': '회전·스케일링·전단을 같은 원에 적용하기', 'pdf': '3쪽 선형대수 1~3번째 요구',
        'concept': '선형 변환은 좌표 벡터에 행렬을 곱해 위치를 바꾸는 규칙이다. 회전은 방향, 스케일링은 축별 길이, 전단은 한 좌표에 다른 좌표의 일부를 더한다. 선형 변환은 원점을 고정하고 직선을 직선으로 보낸다.',
        'example': '사진 편집에서 이미지를 45도 돌리거나 가로를 2배·세로를 절반으로 조절하는 작업을 생각하자. 전단은 간판의 글자를 옆으로 기울이는 효과와 비슷하다. 여기서는 실제 사진 대신 단위 원의 좌표 100개에 같은 좌표 규칙을 적용한다.',
        'steps': [
            ('입력 생성', 'unit_circle()은 θ=linspace(0,2π,100)으로 (cosθ,sinθ)를 쌓아 (100,2) 배열을 만든다. 0과 2π가 모두 포함되어 첫 점과 끝 점은 같다.'),
            ('행렬 정의', 'R(π/4), S(2,0.5), Sh(0.8)를 각각 만든다. 회전 행렬의 열은 회전한 좌표축이며, 전단은 x′=x+0.8y, y′=y다.'),
            ('좌표 변환', '수학의 열벡터 p′=Ap를 여러 행에 저장한 배열로 계산하므로 points @ matrix.T를 사용한다. (100,2)@(2,2)의 결과는 (100,2)다.'),
            ('겹쳐 표시', 'plot_transformations()의 세 서브플롯마다 변환 전 점선을 변환 후 실선과 겹친다. equal 축 비율과 같은 범위를 사용해 그림의 왜곡을 막는다. 회전한 원은 윤곽이 같으므로 첫 점의 반지름선을 함께 표시한다.'),
            ('수치 해석', '제목에 45도, (2,0.5), k=0.8과 원래·변환 후 면적, det, 면적비, 상대오차 및 PASS를 표시한다. 모양이 바뀌어도 세 행렬의 det는 1이어서 면적은 보존된다.')],
        'formula': 'R(θ)=[[cosθ,-sinθ],[sinθ,cosθ]]\nS=[[2,0],[0,0.5]], Sh=[[1,0.8],[0,1]]\n수학: p′=Ap / NumPy 행 저장: P′=P Aᵀ',
        'nodes': [('단위 원 좌표', 'P: (100,2)'), ('변환 행렬 준비', 'R / S / Sh: (2,2)'), ('행 저장 좌표에 적용', 'P @ A.T: (100,2)'), ('전후 겹침과 해석', 'parameters + area + error')],
        'notes': ['회전한 원 자체만 보면 변화가 보이지 않는다. 반지름선이 45도 돌아간 것을 확인한다.', 'S(2,0.5)의 면적은 2×0.5=1배다. 가로가 커졌다는 사실만으로 면적이 증가했다고 말하면 안 된다.'],
        'code': [('src/linear_algebra.py', 'unit_circle'), ('src/linear_algebra.py', 'transform_points'), ('src/linear_algebra.py', 'plot_transformations')],
        'images': ['matrix_transformations.png'], 'notebook': 'mathematics_experiments.ipynb',
    },
    {
        'id': 2, 'title': '행렬식과 측정 면적비를 상대오차로 검증하기', 'pdf': '3쪽: 면적비 오차 1% 이내',
        'concept': '행렬식 det(A)는 선형 변환의 부호가 있는 면적 배율이다. 절댓값은 면적 크기의 비율, 부호는 방향 뒤집힘을 뜻한다. 상대오차는 기준값에 비해 측정값이 얼마나 다른지 비율로 나타낸다.',
        'example': '직사각형 종이를 가로 2배, 세로 절반으로 늘리면 넓이는 그대로다. 거울처럼 뒤집으면 방향은 바뀌어 det가 음수일 수 있지만 종이의 넓이가 음수가 되지는 않는다. 그래서 측정 면적비는 |det(A)|와 비교한다.',
        'steps': [
            ('독립 면적 측정', 'polygon_area()는 인접 꼭짓점의 외적을 합치는 신발끈 공식을 사용한다. det를 이용해 면적을 계산하지 않아야 두 값의 비교가 독립적인 검증이 된다.'),
            ('같은 다각형의 전후 비교', '원래 100개 점의 다각형 면적 A₀와 변환 후 면적 A₁을 구한다. 곡선의 정확한 면적 π와 다각형을 섞지 않고 r=A₁/A₀를 계산한다.'),
            ('이론 배율 계산', 'np.linalg.det(matrix)로 det를 계산한다. 현재 회전·스케일·전단의 det는 모두 양수 1이다.'),
            ('퍼센트 오차와 판정', 'e=|r−|det||/|det|×100을 계산한다. run_required()에서 e≤1을 assert하고 metrics.json에 tolerance_percent=1과 passed를 남긴다. 같은 계산을 그래프 제목에도 표시한다.')],
        'formula': '다각형 면적 = |Σ(xᵢyᵢ₊₁ − yᵢxᵢ₊₁)|/2\nr=A₁/A₀\n상대오차(%)=|r−|det(A)||/|det(A)|×100 ≤ 1',
        'nodes': [('변환 전후 점', 'P / P @ A.T'), ('다각형 면적 측정', 'shoelace: A0, A1'), ('행렬식과 비율 비교', 'r=A1/A0 vs abs(det)'), ('허용오차 판정', 'relative error <= 1%')],
        'notes': ['현재 실험에는 det=0 행렬이 없다. 특이행렬의 면적은 0이 되지만 상대오차 분모도 0이므로 일반화하려면 절대오차 판정이 필요하다.', '다각형의 면적은 π보다 약간 작다. 같은 다각형의 전후 비율은 정확하게 1에 가까우므로 이 근사 오차가 배율 검증을 방해하지 않는다.'],
        'code': [('src/linear_algebra.py', 'polygon_area'), ('scripts/run_experiments.py', 'run_required')],
        'images': [], 'notebook': 'mathematics_experiments.ipynb',
    },
    {
        'id': 3, 'title': 'Power Iteration을 eig의 고유값·고유벡터와 비교하기', 'pdf': '3쪽: 직접 구현 및 eig 비교 오차 5% 이내',
        'concept': '고유벡터 v는 Av=λv를 만족하는 특별한 방향이다. 변환해도 같은 직선 위에 남고 고유값 λ만큼 늘어나거나 부호가 뒤집힌다. Power Iteration은 반복 곱셈에서 가장 큰 절댓값의 고유값 방향이 상대적으로 두드러지는 성질을 사용한다.',
        'example': '매번 같은 변환을 받는 데이터의 움직임을 관찰하면 어떤 방향이 다른 방향보다 더 빠르게 커질 수 있다. A=[[4,1],[1,3]]에서는 약 [0.8507,0.5257] 방향의 성분이 매번 약 4.618배로 늘어난다. 정규화는 크기를 제거하여 이 방향만 추적한다.',
        'steps': [
            ('초기화', 'power_iteration()은 [1,1]을 단위 길이로 만든다. 이 예제는 대칭 양의 정부호 행렬이고 두 고유값은 약 4.618과 2.382다. 초기 벡터가 지배 고유공간에 수직이지 않아야 한다.'),
            ('반복 곱과 정규화', 'product=A@v, v=product/||product||를 반복한다. 작은 고유값 방향의 상대 기여는 대략 (2.382/4.618)^t로 감소한다.'),
            ('고유값과 종료 조건', '단위벡터의 Rayleigh 몫 λ=vᵀAv를 계산한다. 잔차 ||Av−λv||≤1e-6이면 반환하고, 1000번 안에 도달하지 않으면 RuntimeError를 낸다.'),
            ('독립 기준 해 선택', 'scripts/assessment.py의 compare_power_iteration()만 검증 목적으로 np.linalg.eig를 호출한다. abs(eigenvalues)의 argmax로 동일한 지배 고유값과 그 열벡터를 고른다.'),
            ('부호 정렬과 오차 기록', '고유벡터 v와 −v는 같은 방향이다. 내적이 음수면 기준벡터의 부호를 바꾸고 L2 오차를 측정한다. 고유값 상대오차 ≤5%, 벡터 오차 ≤1e-6, 잔차 ≤1e-6을 각각 출력한다.')],
        'formula': 'vₜ₊₁ = A vₜ / ||A vₜ||\nλₜ = vₜᵀ A vₜ\n고유값 오차(%)=|λ−λ_ref|/|λ_ref|×100\n벡터 오차=min(||v−v_ref||, ||v+v_ref||)',
        'nodes': [('행렬과 단위 초기벡터', 'A=[[4,1],[1,3]]'), ('곱셈과 정규화 반복', 'v <- A v / norm(A v)'), ('Rayleigh 몫과 잔차', 'lambda=v.T A v; residual'), ('독립 기준 해와 비교', 'eig + sign alignment')],
        'notes': ['Power Iteration이 일반적으로 구하는 것은 대수적으로 가장 큰 값이 아니라 절댓값이 가장 큰 값이다. 현재 양의 고유값 예제에서는 두 표현이 일치한다.', '고유벡터 비교의 부호 정렬을 빼면 정답인 −v도 큰 오차로 판정할 수 있다. tests/test_assessment.py는 이 실패 모드를 따로 검사한다.'],
        'code': [('src/linear_algebra.py', 'power_iteration'), ('scripts/assessment.py', 'compare_power_iteration')],
        'images': [], 'notebook': 'mathematics_experiments.ipynb',
    },
    {
        'id': 4, 'title': 'SVD의 요청 k와 effective k, 복원 오차·저장량 구분하기', 'pdf': '3쪽 k=10/50/100 비교; 5쪽 64×64 이하 회색조',
        'concept': 'SVD는 행렬을 UΣVᵀ로 분해한다. 큰 특잇값부터 k개의 성분만 더하면 중요 패턴을 남기는 저랭크 근사를 얻는다. 유효 성분 수 effective k는 min(요청 k, 행 수, 열 수)다. 저랭크 근사와 저장량 감소는 같은 말이 아니다.',
        'example': '이미지를 여러 장의 단순한 밝기 패턴의 합으로 생각하자. 큰 패턴 몇 장으로 얼굴이나 윤곽을 남기고 작은 질감은 생략할 수 있다. 64×64 이미지에는 최대 64개의 SVD 성분이 있으므로 100개를 요청해도 100개의 서로 다른 성분은 존재하지 않는다.',
        'steps': [
            ('입력과 출처', 'data/image64.npy는 공개 baboon PGM을 64×64 회색조로 전처리하고 밝기를 0~1로 정규화한 배열이다. data/SOURCE.md와 source_metadata.json에 출처와 전처리 근거가 있다.'),
            ('SVD와 자르기', 'np.linalg.svd(image, full_matrices=False)를 사용한다. svd_compress()는 U의 앞 k열, 특잇값의 앞 k개, Vᵀ의 앞 k행을 반환한다. 실제 k는 min(requested_k,64)다.'),
            ('복원', 'svd_reconstruct()의 (u*singular_values)@vt는 U의 각 열에 특잇값을 곱한 뒤 Vᵀ와 곱한다. 별도 대각행렬을 만들지 않아도 UΣVᵀ와 같다.'),
            ('오차 측정', '원본과 복원 픽셀의 차이에서 MSE와 최대 절대오차를 측정한다. 요청 10/50/100은 각각 실제 10/50/64개를 쓰며 원본과 함께 한 Figure에 표시한다.'),
            ('저장량 해석', '원본은 mn=4096개 값, 인자는 k(m+n+1)=129k개 값이다. k=10은 1290개지만 k=50은 6450개, k=64는 8256개이므로 뒤 두 경우는 인자 값 개수 기준으로 저장량을 줄이지 못한다.')],
        'formula': 'A=UΣVᵀ, Aₖ=(Uₖ * sₖ) Vₖᵀ\nk_eff=min(k_requested,m,n)\nMSE=mean((A−Aₖ)²)\n원본 값 수=mn, 인자 값 수=k_eff(m+n+1)',
        'nodes': [('공개 회색조 이미지', 'A: (64,64), range [0,1]'), ('SVD와 성분 수 제한', 'requested 10/50/100'), ('세 복원 행렬 계산', 'effective 10/50/64'), ('원본과 수치 비교', 'MSE + max error + storage')],
        'notes': ['k=100에서 effective k=64인 이유를 제목과 보고서에 함께 표시한다. 이미지 크기를 100 이상으로 키우면 PDF의 데이터 가이드를 벗어난다.', '표의 저장 비율은 동일 dtype의 값 개수 기준이다. PNG 파일의 압축률이나 실제 파일 바이트 수를 측정한 것이 아니다.'],
        'code': [('src/linear_algebra.py', 'svd_compress'), ('src/linear_algebra.py', 'svd_reconstruct'), ('src/linear_algebra.py', 'plot_svd_reconstructions')],
        'images': ['svd_reconstructions.png'], 'notebook': 'mathematics_experiments.ipynb',
    },
    {
        'id': 5, 'title': '중심차분 미분과 해석적 미분의 허용오차 판정', 'pdf': '3쪽: x²의 x=3 미분, 오차 1e-4 이내',
        'concept': '미분은 입력을 조금 바꿀 때 함수값이 얼마나 변하는지 나타낸다. 중심차분은 기준점의 왼쪽과 오른쪽 함수값을 사용해 접선의 기울기를 근사한다. 충분히 매끄러운 함수에서 절단오차는 보통 O(h²)지만 h를 지나치게 줄이면 부동소수점 뺄셈 오차가 커질 수 있다.',
        'example': '차량 위치를 t−h와 t+h에서 기록하고 이동 거리를 2h로 나누면 t 시점의 속도를 근사할 수 있다. 이 과제는 시간 대신 x, 위치 대신 f(x)=x²를 사용해 근사값과 정확한 변화율 2x를 비교한다.',
        'steps': [('함수와 기준점', 'f(x)=x², x=3, 해석적 미분 f′(3)=2×3=6을 기준 해로 둔다.'),
                  ('간격 선택', 'central_difference()의 기본 h=1e-5를 사용한다. f(3+h)와 f(3−h)를 따로 계산한다.'),
                  ('중심차분 계산', '(f(x+h)−f(x−h))/(2h)를 반환한다. x²는 대수적으로 2x가 정확히 남지만 실제 컴퓨터에서는 반올림 때문에 작은 오차가 생긴다.'),
                  ('오차 판정과 출력', '절대오차 |numeric−6|를 허용오차 1e-4와 직접 비교한다. run_required()가 assert하고 값·h·정답·오차·tolerance·passed를 모두 기록한다.')],
        'formula': 'f′(x)≈[f(x+h)−f(x−h)]/(2h)\n[(x+h)²−(x−h)²]/(2h)=4xh/(2h)=2x\n절대오차=|numeric−6| ≤ 1e-4',
        'nodes': [('함수와 기준 미분', 'f=x^2, x=3, exact=6'), ('양쪽 함수값 계산', 'h=1e-5; x+h / x-h'), ('대칭 변화율 계산', '(f_plus-f_minus)/(2h)'), ('절대오차로 판정', 'error <= 1e-4: PASS')],
        'notes': ['허용오차 1e-4는 상대오차가 아니라 값 6과의 절대 차이다.', 'h가 작을수록 무조건 더 정확하다는 결론은 맞지 않는다. 이 예제의 근사 오차와 일반 함수의 오차를 구분한다.'],
        'code': [('src/calculus.py', 'central_difference'), ('src/calculus.py', 'derivative_sensitivity'), ('scripts/run_experiments.py', 'run_required')],
        'images': ['derivative_sensitivity.png'], 'notebook': 'mathematics_experiments.ipynb',
    },
    {
        'id': 6, 'title': '등고선의 법선 방향과 기울기 화살표의 길이 읽기', 'pdf': '3쪽: 등고선·여러 점 Gradient·수직 확인',
        'concept': '기울기 ∇f는 좌표별 편미분을 모은 벡터이며 가장 빠르게 함수값이 증가하는 방향을 가리킨다. 등고선은 함수값이 같은 점의 모임이다. 등고선을 따라 이동할 때 함수값이 변하지 않으므로 그 접선과 기울기의 내적은 0이다.',
        'example': '지형도에서 같은 높이의 선을 따라 걸으면 고도가 유지된다. 가장 가파르게 올라가는 방향은 그 선을 가로지르는 방향이다. 경사하강법은 반대로 −∇f 방향을 사용한다. 이 예제에서는 원점에서 멀어질수록 x²+y²가 커진다.',
        'steps': [('등고선 계산', 'plot_gradient()는 meshgrid로 f=x²+y²를 계산하고 f=1,4,9의 원형 등고선을 그린다.'),
                  ('표본점과 수치 기울기', '반지름 2인 f=4 등고선에 45도 간격의 8점을 놓는다. numerical_gradient()는 각 좌표만 ±h 움직여 편미분한다. 정확한 기울기는 (2x,2y)다.'),
                  ('길이와 방향 표시', 'quiver의 angles=xy, scale_units=xy, scale=5를 사용한다. 그려진 길이는 기울기 크기의 1/5다. 반지름 2에서 ||∇f||=4이므로 그림에서는 0.8 좌표 단위 길이로 표시된다.'),
                  ('수직성 검증', '해석적 접선 t=(−y,x)와 수치 기울기의 내적을 별도 점들에서 측정한다. 이론상 (2x,2y)·(−y,x)=0이며, 작은 실제 오차를 보고서에 남긴다. 범례 화살표는 크기 4와 표시 길이 0.8을 설명한다.')],
        'formula': '∇f=(2x,2y), tangent=(−y,x)\n∇f·t=−2xy+2yx=0\nf=4 위에서는 ||∇f||=4\n표시 화살표=∇f/5, 표시 길이=0.8',
        'nodes': [('같은 함수값의 등고선', 'levels=1,4,9'), ('원 위 여덟 점의 편미분', 'points on r=2; h=1e-5'), ('방향과 길이 표시', 'quiver scale=5; norm=4'), ('법선 방향 검증', 'gradient dot tangent ~ 0')],
        'notes': ['화살표는 올라가는 방향이다. 다음 항목의 경사하강법이 움직이는 방향은 이 화살표의 반대다.', 'quiver 스케일은 시각화용이며 실제 numerical_gradient()의 값을 줄이지 않는다.'],
        'code': [('src/calculus.py', 'numerical_gradient'), ('src/calculus.py', 'plot_gradient')],
        'images': ['gradient_contours.png'], 'notebook': 'mathematics_experiments.ipynb',
    },
    {
        'id': 7, 'title': '2→2→1 신경망의 손계산과 연쇄 법칙을 단계별 유도하기', 'pdf': '3~4쪽: 고정 예제·순전파·여섯 미분·shape',
        'concept': '순전파는 입력에서 예측과 손실을 계산하는 과정이다. 역전파는 손실의 변화율을 출력에서 입력 쪽으로 전달하는 연쇄 법칙 계산이다. Sigmoid는 실수를 0~1로 바꾸고, BCE는 이진 정답의 확률이 작을수록 큰 손실을 준다.',
        'example': '두 특징으로 시험 합격 여부를 예측하는 작은 모델을 상상하자. 현재 정답이 합격(1)인데 예측 확률이 0.6473이면, 손실은 합격 확률을 높이는 방향의 가중치 변화를 요구한다. 과제의 [1,0]과 소수 가중치는 학습 데이터가 아니라 미분 과정을 확인하는 고정 숫자다.',
        'steps': [('입력과 shape 고정', 'fixed_example()에서 x=[1,0] (2,), W1=[[.1,.2],[.3,.4]] (2,2), b1=[0,0] (2,), W2=[.5,.6] (2,), b2=0 (), y=1 ()를 가져온다. W1의 한 행은 은닉 뉴런 하나다.'),
                  ('은닉층 손계산', 'z1=W1@x+b1=[.1,.3] (2,). a1=σ(z1)=[.5249791875,.5744425168] (2,). σ′(z)=σ(z)(1−σ(z))를 다음 역전파에서 사용한다.'),
                  ('출력과 BCE', 'z2=.5×.5249791875+.6×.5744425168=.6071551038 (). ŷ=σ(z2)=.6472915700 (). y=1이므로 L=−ln ŷ=.4349584369 ().'),
                  ('출력의 연쇄 법칙', 'dL/dŷ=−y/ŷ+(1−y)/(1−ŷ)=−1.5448988468 (). 여기에 dŷ/dz2=ŷ(1−ŷ)를 곱하면 δ2=ŷ−y=−.3527084300 (). dW2=δ2×a1=[−.1851645850,−.2026107182] (2,).'),
                  ('은닉층으로 전달', 'da1=δ2×W2=[−.1763542150,−.2116250580] (2,). δ1=da1⊙a1⊙(1−a1)=[−.0439785158,−.0517335044] (2,). 이때 ⊙는 원소별 곱이다.'),
                  ('첫 가중치와 편향', 'dW1=outer(δ1,x)=[[−.0439785158,0],[−.0517335044,0]] (2,2). 입력 두 번째 성분이 0이라 그 열의 기울기도 0이다. 편향의 미분은 db1=δ1 (2,), db2=δ2 ()다.')],
        'formula': 'z₁=W₁x+b₁, a₁=σ(z₁), z₂=W₂a₁+b₂, ŷ=σ(z₂)\nδ₂=(∂L/∂ŷ)ŷ(1−ŷ)=ŷ−y\n∂L/∂W₂=δ₂a₁, ∂L/∂a₁=δ₂W₂\nδ₁=(δ₂W₂)⊙a₁⊙(1−a₁)\n∂L/∂W₁=δ₁xᵀ',
        'nodes': [('고정 입력과 은닉층', 'z1=[0.1,0.3]; a1=(2,)'), ('출력 확률과 손실', 'y_pred=0.6473; L=0.4350'), ('출력 변화율 전달', 'dz2=-0.3527; dW2=(2,)'), ('은닉 변화율과 가중치', 'dz1=(2,); dW1=(2,2)')],
        'notes': ['중간 계산은 반올림하지 않는다. .5250과 .5744를 다음 식에 다시 넣으면 원래 계산과 다른 오차가 누적된다.', 'PDF 3쪽 y_true는 빈칸이므로 7쪽의 1을 사용한다. 7쪽 참고 숫자 z2=.6071, dz1[1]=−.0513은 정확한 재계산의 .6072, −.0517과 다르다.'],
        'code': [('src/backprop.py', 'fixed_example'), ('src/backprop.py', 'forward_backward')],
        'images': [], 'notebook': 'backprop_derivation.ipynb',
    },
    {
        'id': 8, 'title': '손계산과 NumPy의 소수점 4자리 일치를 표로 검증하기', 'pdf': '4쪽: 동일 계산을 수행하고 소수점 4자리 일치 확인',
        'concept': '계산의 검증은 값이 비슷해 보이는 것과 다르다. 비교 규칙을 먼저 정하고 각 중간 결과의 모양과 값을 검사해야 한다. 여기서는 반올림된 숫자의 동일성을 검사하고, 실제 미분이 맞는지는 별도의 중심차분으로 다시 확인한다.',
        'example': '영수증을 검산할 때 총액만 맞으면 품목별 오류가 상쇄될 수 있다. 신경망에서도 최종 손실만 맞으면 중간 미분의 오류를 놓칠 수 있으므로 z1부터 dW1까지 개별 체크포인트를 비교한다.',
        'steps': [('독립 손계산 기준', 'scripts/assessment.py의 hand_checkpoints()는 앞 항목의 수식으로 구한 4자리 상수 11개를 보관한다. forward_backward()의 출력으로 기준을 자동 생성하지 않는다.'),
                  ('실제 구현 실행', 'forward_backward(**fixed_example())에서 반올림하지 않은 순전파 5개, 필수 역전파 6개의 값을 가져온다.'),
                  ('shape와 값 동시 비교', 'compare_hand_calculation()은 양쪽 np.round(...,4)를 계산한다. shape가 같은지 확인하고 np.array_equal로 모든 원소가 같은지 비교한다. 브로드캐스팅으로 모양 오류를 숨기지 않는다.'),
                  ('검증표와 로그 보존', '각 행에 group, name, shape, hand_rounded_4, numpy_rounded_4, passed를 기록한다. 노트북에도 손계산/NumPy/상태 표를 출력한다. 테스트는 틀린 −.0513이나 잘못된 (1,2) shape가 FAIL인지 확인한다.'),
                  ('미분 자체의 독립 검증', '노트북은 W1,b1,W2,b2의 모든 성분에 대해 손실을 중심차분하여 역전파 미분과 atol=1e-8로 대조한다. 이는 상수 표와 구현이 함께 틀렸을 가능성을 줄이는 추가 검사다.')],
        'formula': 'shape(hand)=shape(numpy)\nround(hand,4)=round(numpy,4), 모든 원소 일치\n수치 검산: dL/dθ≈[L(θ+h)−L(θ−h)]/(2h)',
        'nodes': [('수식에서 구한 기준표', '11 hand checkpoints'), ('NumPy 실제 중간값', 'forward + backward'), ('shape와 4자리 대조', 'round(...,4); array_equal'), ('모든 행의 통과 확인', 'PASS per row + finite diff')],
        'notes': ['소수 4자리 일치는 원래 실수값이 완전히 같다는 뜻이 아니다. 요구된 표시 정밀도에서 같은 값을 갖는다는 뜻이다.', 'PDF의 오타를 기준 상수로 쓰면 올바른 코드가 실패한다. 원래 입력과 수식으로 기준값을 먼저 도출한다.'],
        'code': [('scripts/assessment.py', 'hand_checkpoints'), ('scripts/assessment.py', 'compare_hand_calculation'), ('tests/test_assessment.py', 'AssessmentTests')],
        'images': [], 'notebook': 'backprop_derivation.ipynb',
    },
    {
        'id': 9, 'title': 'lr=0.1의 100회 GD와 PDF 반경 0.1 기준 확인', 'pdf': '4쪽: lr=.1, 100회, 원점 반경 .1 이내',
        'concept': '경사하강법은 현재 좌표에서 기울기의 반대 방향으로 학습률만큼 이동한다. 학습률은 한 번에 얼마나 움직일지 정하는 계수다. 원점에 도달했다는 주장은 좌표나 손실뿐 아니라 요구된 반경 기준으로 확인해야 한다.',
        'example': '공이 그릇 바닥으로 내려가는 방향을 작은 걸음으로 따라가는 상황을 생각하자. 과제의 함수는 둥근 그릇 f=x²+y²이고 최저점은 (0,0)이다. 실제 알고리즘은 물리 시뮬레이션이 아니라 매번 −lr×∇f를 더하는 수치 반복이다.',
        'steps': [('정확한 시작 조건', 'VanillaGD(lr=.1), initial=(5,5), circle_gradient=2θ, steps=100을 사용한다. 초기 반경은 √50≈7.0711이다.'),
                  ('첫 업데이트', '기울기는 (10,10)이므로 (5,5)−.1(10,10)=(4,4)다. 매번 θ_next=.8θ가 되어 크기가 감소한다.'),
                  ('100회와 101개 저장점', 'optimize()는 초기점과 매 업데이트 후 좌표를 보존하므로 history.shape=(101,2)다. 마지막 점은 약 (1.0185e-9,1.0185e-9)다.'),
                  ('PDF 기준 자동 판정', 'convergence_summary()는 마지막 반경 ||θ||를 구해 ≤.1과 비교한다. 사용자 평가에 나온 반경 1 판정도 함께 기록하지만 요구 충족의 기준은 더 엄격한 .1이다.'),
                  ('경로와 손실 해석', 'circle_paths.png에 점선 경로, 시작 원형 표식, 종료 x 표식을 표시한다. circle_loss.png는 업데이트 수별 손실이다. 두 좌표가 매번 같은 비율로 줄어 직선 경로를 따른다.')],
        'formula': 'θₜ₊₁=θₜ−0.1(2θₜ)=0.8θₜ\nθ₁₀₀=0.8¹⁰⁰(5,5)\n반경 r₁₀₀=√50×0.8¹⁰⁰≈1.4404e-9 ≤ 0.1',
        'nodes': [('원형 함수와 시작점', 'f=x^2+y^2; (5,5)'), ('학습률 0.1 업데이트', 'theta_next=0.8 theta'), ('정확히 100회 반복', 'history: (101,2)'), ('PDF 반경 기준 판정', 'radius <= 0.1: PASS')],
        'notes': ['반경 1을 통과했다고 PDF를 충족했다고 판단하면 안 된다. 실제 PDF는 반경 0.1이다.', 'history의 행 수와 업데이트 횟수는 1만큼 다르다. 초기점은 업데이트 0으로 센다.'],
        'code': [('src/optimizer.py', 'VanillaGD'), ('src/optimizer.py', 'optimize'), ('scripts/run_experiments.py', 'convergence_summary')],
        'images': ['circle_paths.png', 'circle_loss.png'], 'notebook': 'mathematics_experiments.ipynb',
    },
    {
        'id': 10, 'title': '학습률 0.5·1.0·1.1의 안정·진동·발산 구분', 'pdf': '4쪽: lr≥.5 발산 그래프 문구의 수학적 해석',
        'concept': '발산은 반복할수록 최저점에서 멀어지고 손실이 커지는 현상이다. 높은 학습률은 최저점을 지나쳐 반대편으로 이동하게 할 수 있지만, 발산의 경계는 함수의 곡률에 따라 달라진다. 경계 학습률을 모든 함수에서 .5라고 정할 수 없다.',
        'example': '계단을 내려갈 때 걸음이 너무 크면 반대편으로 넘어진다는 비유가 가능하다. 하지만 원점까지 정확히 한 번에 이동하는 걸음도 있다. 이 함수에서는 lr=.5가 바로 그런 경우라서 높은 값이라는 이유만으로 발산이라고 부르면 안 된다.',
        'steps': [('점화식 유도', 'f=x²+y²이면 ∇f=2θ라서 θ_next=(1−2lr)θ다. 절댓값 배율 |1−2lr|가 1보다 작아야 좌표 크기가 줄어든다.'),
                  ('학습률 .5의 반례', 'lr=.5이면 배율은 0이다. 시작점 (5,5)에서 첫 업데이트에 (0,0)에 도달하고 이후 손실은 0이다. 이것은 발산이 아니라 정확한 수렴이다.'),
                  ('경계와 발산 실험', 'lr=1은 배율 −1이어서 (5,5)와 (−5,−5)를 오가고 손실 50이 유지된다. lr=1.1은 배율 −1.2여서 부호를 바꾸며 반경은 매번 1.2배, 손실은 1.44배 증가한다.'),
                  ('같은 조건의 그래프', 'lr=.1/.5/1/1.1을 같은 (5,5), 20회 조건으로 실행한다. learning_rate_paths.png에 넓은 좌표 범위의 경로를, learning_rate_loss.png에 손실 곡선을 모두 표시한다.'),
                  ('판정과 정직한 요구 해석', 'circle_stability()는 이론 regime과 실측 반경비를 기록한다. lr=1.1은 .5 이상 범위에 속하는 실제 발산 사례를 충족한다. 다만 “.5 이상 모두 발산”이라는 해석은 틀리므로 결과에 억지로 맞추지 않는다.')],
        'formula': '배율 a=1−2lr; fₜ₊₁=a²fₜ\n0<lr<1: 수렴 / lr=1: 크기 일정 진동 / lr>1: 발산\nlr=.5: a=0, 한 번에 원점\nlr=1.1: r₂₀/r₀=1.2²⁰≈38.3376',
        'nodes': [('고정 함수에서 점화식', 'theta_next=(1-2lr)theta'), ('.5: 한 번에 원점', 'factor=0; final loss=0'), ('1.0: 진동 / 1.1: 발산', '|factor|=1 / 1.2'), ('이론과 실측 곡선 대조', '20 steps; radius/loss ratios')],
        'notes': ['손실 로그 그래프는 0을 표시할 수 없어서 시각화에서만 max(loss,1e-20)를 사용한다. metrics.json의 실제 lr=.5 손실은 0이다.', '타원 함수는 y 방향 곡률이 20이어서 GD 안정 범위가 0<lr<.1이다. 원형 함수의 경계 1을 타원에 그대로 적용하면 안 된다.'],
        'code': [('src/optimizer.py', 'circle_gradient'), ('scripts/assessment.py', 'circle_stability'), ('src/optimizer.py', 'plot_loss_curves')],
        'images': ['learning_rate_paths.png', 'learning_rate_loss.png', 'ellipse_learning_rate_loss.png'], 'notebook': 'mathematics_experiments.ipynb',
    },
    {
        'id': 11, 'title': 'VanillaGD와 Momentum을 동일 초기화로 비교하기', 'pdf': '4쪽: Momentum β=.9 및 같은 Figure 경로 비교; 5쪽 seed=42',
        'concept': 'Momentum은 이전 기울기를 속도 상태에 누적하여 같은 방향의 이동을 이어가는 방법이다. 클래스의 속도가 다음 호출까지 남기 때문에 공정한 비교에는 같은 함수·초기점·학습률뿐 아니라 독립적인 상태 초기화도 필요하다.',
        'example': '매 순간 경사만 보고 움직이는 사람과 이전 움직임의 관성을 가진 수레를 비교해 보자. 과거에 움직인 수레를 그대로 다시 출발시키면 출발 속도가 달라져 비교가 불공정하다. 새 Momentum 인스턴스로 시작하는 것은 속도 0인 수레를 준비하는 것과 같다.',
        'steps': [('동일 초기점과 시드', 'run_required()는 np.random.seed(42)를 고정한다. 모든 경로의 initial=(5,5)다. 현재 함수와 기울기는 결정적이라 시드가 좌표를 바꾸지는 않지만 재현성 조건으로 기록한다.'),
                  ('GD 업데이트', 'VanillaGD.step()은 point−lr×gradient를 반환한다. 이전 업데이트의 상태를 보관하지 않는다.'),
                  ('Momentum 초기화와 정의', 'Momentum은 VanillaGD를 상속한다. velocity=None에서 시작하며 첫 step에서 zeros_like(gradient)로 만든다. v=βv+g, θ_next=θ−lr×v, β=.9를 사용한다.'),
                  ('새 객체와 복사', '원형·타원형·학습률·보너스 실험마다 새 옵티마이저를 만든다. optimize()는 초기점을 새 배열로 만들고 history에는 copy()를 저장해 과거 좌표가 수정되지 않게 한다.'),
                  ('비교 범위 명시', '원형은 둘 다 lr=.1·100회, 타원은 둘 다 lr=.01·200회다. reports/metrics.json의 reproducibility에 시드·초기점·초기속도·반복 횟수·독립 인스턴스를 명시한다.')],
        'formula': 'GD: θₜ₊₁=θₜ−lr gₜ\nMomentum: vₜ=.9vₜ₋₁+gₜ, θₜ₊₁=θₜ−lr vₜ\nv_initial=(0,0), θ_initial=(5,5)\n본 구현은 g 앞에 (1−β)를 곱하지 않는 누적 관례',
        'nodes': [('공통 실험 조건', 'seed=42; initial=(5,5)'), ('서로 다른 새 인스턴스', 'GD / Momentum; v0=0'), ('같은 함수와 반복 수', 'circle .1 / ellipse .01'), ('경로와 속도 기준 비교', 'fresh state + copied history')],
        'notes': ['v=βv+(1−β)g인 지수이동평균 관례와 현재 구현을 섞으면 같은 lr 숫자라도 실제 이동량이 달라진다.', 'Momentum이 모든 함수에서 항상 더 빠르거나 최종 손실이 작다고 주장하지 않는다. 원형의 100회 최종 손실은 GD가 더 작다.'],
        'code': [('src/optimizer.py', 'VanillaGD'), ('src/optimizer.py', 'Momentum'), ('src/optimizer.py', 'optimize')],
        'images': [], 'notebook': 'mathematics_experiments.ipynb',
    },
    {
        'id': 12, 'title': '타원형 함수에서 Momentum의 수렴 속도와 경로 해석', 'pdf': '4쪽: f=x²+10y²에서 GD와 Momentum 비교',
        'concept': '함수의 곡률은 방향별로 달라질 수 있다. 타원형 함수의 y 방향은 x 방향보다 10배 가파르므로 같은 학습률에서 두 좌표의 수렴 속도가 다르다. Momentum의 누적 상태는 완만한 방향의 이동을 가속할 수 있지만 초과 이동과 진동도 일으킬 수 있다.',
        'example': '좁고 긴 골짜기를 내려가는 경우를 상상하자. 옆 벽 방향의 경사는 가파르고 골짜기를 따라가는 방향은 완만하다. 매번 현재 경사만 따라가면 완만한 방향의 진행이 느리다. 누적된 움직임은 그 방향의 진행을 돕지만 항상 매끄러운 경로를 만들지는 않는다.',
        'steps': [('함수와 정확한 기울기', 'ellipse_loss()는 x²+10y², ellipse_gradient()는 (2x,20y)를 반환한다. Hessian은 diag(2,20)으로 두 방향 곡률이 다르다.'),
                  ('같은 학습률 선택', '둘 다 lr=.01, (5,5), 200회로 실행한다. GD에서 x_next=.98x, y_next=.8y이므로 y가 빨리 작아지고 x가 길게 남는다.'),
                  ('공통 그래프에 경로', 'plot_paths()에 GD와 Momentum의 두 history를 함께 전달한다. 점선 경로, 시작 o, 종료 x, 학습률·β 범례로 조건과 이동 방향을 읽는다.'),
                  ('속도 기준 정의', '같은 손실 임계값 .01로 첫 도달 업데이트와 이후 끝까지 .01 이하를 유지하는 최초 업데이트를 구분한다. 첫 도달만으로 영구 수렴을 단정하지 않는다.'),
                  ('실측 결과 해석', '기존 실험 조건에서는 GD 194회, Momentum 78회에 처음 .01 이하가 된다. 손실 곡선의 진동과 마지막 값까지 함께 읽어 “이 조건과 기준에서 Momentum이 빠르다”고 설명한다.')],
        'formula': 'f=x²+10y², ∇f=(2x,20y)\nGD lr=.01: x_next=.98x, y_next=.8y\n속도 기준: 첫 t such that f(θₜ)≤.01\n유지 기준: 모든 u≥t의 관측 f(θᵤ)≤.01',
        'nodes': [('방향별 곡률이 다른 함수', 'Hessian=diag(2,20)'), ('동일 lr=.01 / 200회', 'initial=(5,5); beta=.9'), ('경로와 손실 동시 관찰', 'dashed path + log loss'), ('명시한 기준으로 속도 비교', 'first hit vs sustained hit')],
        'notes': ['이 유지 판정은 기록된 200회 구간 안에서의 판정이다. 무한 시간의 수렴을 수치 로그만으로 증명하는 것은 아니다.', 'PDF 8쪽 lr=.05는 참고 예시다. 필수 비교의 학습률은 고정되어 있지 않아 같은 lr=.01로 비교한다.'],
        'code': [('src/optimizer.py', 'ellipse_loss'), ('src/optimizer.py', 'ellipse_gradient'), ('src/optimizer.py', 'plot_paths'), ('scripts/run_experiments.py', 'convergence_summary')],
        'images': ['ellipse_paths.png', 'ellipse_loss.png'], 'notebook': 'mathematics_experiments.ipynb',
    },
    {
        'id': 13, 'title': '정규 PDF 두 종과 베르누이 PMF 두 종을 비교하기', 'pdf': '4쪽: N(0,1)/N(2,.5), B(.3)/B(.7)',
        'concept': '연속형 PDF는 밀도이고 구간 아래 면적이 확률이다. 이산형 PMF는 각 값 자체의 확률이다. 정규분포 N(μ,σ²)는 중심과 퍼짐, 베르누이 B(p)는 성공(1)과 실패(0)의 두 상태를 표현한다.',
        'example': '센서 측정 오차처럼 연속적인 값을 설명할 때 정규분포를 사용할 수 있다. 같은 센서의 오차 중심이 2로 이동하고 분산이 .5가 되면 그래프가 오른쪽으로 이동하며 좁고 높아진다. 한 번의 제품 클릭 여부는 베르누이로 나타낼 수 있고 클릭 확률 .3이면 비클릭 확률은 .7이다.',
        'steps': [('정규식 직접 계산', 'ProbabilityLoss.normal_pdf()는 exp(−(x−μ)²/(2variance))/sqrt(2πvariance)를 NumPy로 계산한다. 두 번째 인수는 표준편차가 아니라 분산이다.'),
                  ('정규 PDF 비교 Figure', 'plot_normal_distributions()는 x∈[−4,6]의 500개 점에서 N(0,1), N(2,.5)를 같은 축에 그린다. 후자의 표준편차는 √.5≈.7071이다.'),
                  ('베르누이 식과 막대', 'bernoulli_pmf([0,1],p)는 [1−p,p]다. p=.3과 .7의 두 막대를 x=0,1 주변에 나란히 놓고 y축 범위를 0~1로 고정한다.'),
                  ('출력의 증거', 'probability_loss.ipynb에서 plt.show()를 실행해 두 Figure의 PNG 출력을 노트북 안에 저장한다. outputs/normal_pdf.png와 bernoulli_pmf.png도 함께 제공한다.'),
                  ('정규화 검산', '넓은 [−10,10] 구간에서 PDF를 사다리꼴 적분해 약 1인지, 베르누이 두 확률의 합이 1인지 확인한다. 적분 구간과 근사 방법을 명시한다.')],
        'formula': 'Normal PDF=exp(−(x−μ)²/(2σ²))/√(2πσ²)\nBernoulli PMF=P(Y=y)=pʸ(1−p)¹⁻ʸ\nPDF: ∫p(x)dx=1 / PMF: P(0)+P(1)=1',
        'nodes': [('연속과 이산 변수 구분', 'density vs probability mass'), ('두 정규 PDF 계산', 'N(0,1) / N(2,0.5)'), ('두 베르누이 PMF 계산', 'B(.3) / B(.7)'), ('노트북 그림과 정규화 검산', '2 figures; integral/sum ~ 1')],
        'notes': ['PDF 높이는 한 점의 확률이 아니므로 밀도가 1보다 커도 그 자체로 오류가 아니다.', '정규 N(2,.5)의 분산 규약을 숨기지 않는다. 표준편차 .5로 구현하면 요청한 N(μ,σ²) 해석과 다른 곡선이다.'],
        'code': [('src/probability.py', 'ProbabilityLoss.normal_pdf'), ('src/probability.py', 'ProbabilityLoss.bernoulli_pmf'), ('src/probability.py', 'plot_normal_distributions'), ('src/probability.py', 'plot_bernoulli_distributions')],
        'images': ['normal_pdf.png', 'bernoulli_pmf.png'], 'notebook': 'probability_loss.ipynb',
    },
    {
        'id': 14, 'title': '안정적인 Softmax 구현과 합 오차 1e-6 검증', 'pdf': '4쪽: Softmax 출력 합과 1의 차이 ≤1e-6',
        'concept': 'Softmax는 임의의 실수 점수(logits)를 양수이며 합이 1인 벡터로 바꾼다. 모든 로짓에 같은 상수를 더하거나 빼도 결과는 같다. 최대 로짓을 빼면 가장 큰 지수의 입력이 0이 되어 큰 양수의 지수 overflow를 피할 수 있다.',
        'example': '모델이 사과·배·복숭아에 점수 [1000,1001,1002]를 줬다고 하자. 점수는 확률이 아니지만 Softmax를 통과하면 약 [.0900,.2447,.6652]가 된다. 가장 높은 점수가 가장 높은 확률을 얻으며, 세 선택지의 확률 합은 1이다. 높은 확률이 실제 정확도 보장을 뜻하지는 않는다.',
        'steps': [('입력과 최대값', 'ProbabilityLoss.softmax()는 1차원 로짓을 float 배열로 만들고 max=1002를 뺀다. shifted=[−2,−1,0]이다.'),
                  ('지수 계산', 'exp(shifted)=[.1353353,.3678794,1]을 계산한다. exp(1000)을 직접 계산하지 않는다.'),
                  ('정규화', '지수 값들을 전체 합 약 1.5032147로 나눈다. 모든 원소가 양수이고 합이 부동소수점 정밀도 내에서 1이 된다.'),
                  ('절대 허용오차', 'abs(probabilities.sum()−1)≤1e-6을 직접 assert한다. metrics.json과 노트북 출력에 합·절대오차·허용오차·PASS를 모두 표시한다.'),
                  ('추가 성질 검증', '같은 함수의 [0,1,2] 출력과 비교하여 상수 이동 불변성을 확인한다. 큰 입력으로도 유한한 확률을 반환하는지 테스트한다.')],
        'formula': 'm=max(z), qⱼ=exp(zⱼ−m)/Σₖexp(zₖ−m)\n[1000,1001,1002]−1002=[−2,−1,0]\n|Σq−1|≤1e-6',
        'nodes': [('큰 실수 로짓 입력', 'z=[1000,1001,1002]'), ('최대값 빼기', 'shifted=[-2,-1,0]'), ('지수와 합으로 정규화', 'exp(shifted)/sum(exp)'), ('확률 합 오차 검사', 'abs(sum-1) <= 1e-6')],
        'notes': ['현재 함수의 계약은 유한한 1차원 로짓이다. 여러 샘플의 배치를 위한 axis 인수를 구현했다고 설명하지 않는다.', 'np.isclose의 기본 rtol까지 사용하면 요구한 절대오차만의 기준보다 느슨해질 수 있다. 이 항목은 직접 절대 차를 비교한다.'],
        'code': [('src/probability.py', 'ProbabilityLoss.softmax'), ('scripts/run_experiments.py', 'run_required')],
        'images': [], 'notebook': 'probability_loss.ipynb',
    },
    {
        'id': 15, 'title': 'MSE↔정규 MLE, BCE·CE↔분포 MLE를 단계별 유도하기', 'pdf': '4쪽: MSE-MLE, Bernoulli/categorical CE-MLE 유도',
        'concept': '우도(likelihood)는 관측된 정답을 고정하고 어떤 모델 파라미터가 그 정답에 큰 확률을 주는지 평가하는 함수다. MLE는 우도를 최대화하는 파라미터를 고른다. 음의 로그우도(NLL)를 최소화하는 것과 같으며, 정답의 분포 가정에 따라 MSE 또는 교차엔트로피가 나온다.',
        'example': '온도 예측에서 측정 오차가 평균 0의 같은 분산을 갖는 정규분포라면 큰 제곱 오차의 예측은 관측 정답의 우도가 작아진다. 클릭/비클릭은 베르누이 확률, 사과/배/복숭아 중 하나의 정답은 카테고리 확률로 설명한다. 두 분류 문제에서는 정답에 낮은 확률을 주면 −log 확률이 커진다.',
        'steps': [('공통 출발: 독립 표본', '관측 (xᵢ,yᵢ)가 조건부 독립이면 전체 우도는 ∏p(yᵢ|xᵢ,θ)다. 로그는 증가 함수이므로 argmax L=argmax log L=argmin(−log L)다. 곱은 합으로 바뀐다.'),
                  ('정규 가정', 'yᵢ=fθ(xᵢ)+εᵢ, εᵢ~N(0,σ²), σ²>0은 모든 표본에서 같은 고정값이라고 둔다. log p=−.5 log(2πσ²)−(yᵢ−fθ(xᵢ))²/(2σ²)다.'),
                  ('MSE 결론', 'NLL=n/2 log(2πσ²)+(1/(2σ²))Σ(yᵢ−fθ(xᵢ))²다. 첫 항은 θ와 무관하고 두 번째 계수는 양수다. 상수를 제거하고 n으로 나눠도 최소점은 같아서 argmin NLL=argmin MSE다.'),
                  ('베르누이 가정과 BCE', 'yᵢ∈{0,1}, qᵢ=fθ(xᵢ)라면 p(yᵢ)=qᵢ^yᵢ(1−qᵢ)^(1−yᵢ). 곱의 로그를 전개하면 NLL=−Σ[yᵢlog qᵢ+(1−yᵢ)log(1−qᵢ)]가 되어 BCE의 합이다.'),
                  ('카테고리 가정과 CE', 'one-hot yᵢc와 Softmax qᵢc를 쓰면 p(yᵢ)=∏c qᵢc^yᵢc. NLL=−ΣᵢΣc yᵢc log qᵢc로 categorical CE의 합이다. one-hot에서는 정답 클래스 한 항만 남는다.'),
                  ('실제 수치로 검산', 'probability_loss.ipynb는 정규 PDF를 직접 대입한 NLL과 C+n×MSE/(2σ²)를 비교한다. 베르누이 PMF의 우도 곱·BCE 합, 카테고리 확률의 우도 곱·CE 합도 독립적으로 대조한다. loss_likelihood_checks.json에 오차와 PASS를 저장한다.')],
        'formula': '독립 표본: L(θ)=∏ᵢp(yᵢ|xᵢ,θ)\nNormal: NLL=C+n×MSE/(2σ²)\nBernoulli: NLL=ΣᵢBCE(yᵢ,qᵢ)\nCategorical: NLL=ΣᵢCE(yᵢ,qᵢ)\nargmax L = argmin NLL = 해당 손실의 argmin',
        'nodes': [('정답 분포와 독립성 가정', 'Gaussian / Bernoulli / Cat.'), ('전체 우도는 확률의 곱', 'L=product p(y_i|x_i)'), ('음의 로그로 합 전개', 'NLL=-sum log p'), ('손실 함수와 최소점 연결', 'MSE / BCE / CE + checks')],
        'notes': ['MSE와 정규 NLL의 숫자가 같다는 결론이 아니다. 고정 분산 가정 아래 최소화하는 θ가 같다. 표본마다 분산이 다르면 가중 제곱오차가 나온다.', '평균 CE와 합 CE도 n이 고정이면 최소점이 같지만 값과 기울기 배율은 다르다. 이 노트북은 자연로그를 사용하므로 단위는 nats다.', '확률 0이나 1의 경계에서 log가 무한대가 될 수 있다. 수치 검산 예제는 모든 필요한 확률이 0과 1 사이에 있는 경우를 사용한다.'],
        'code': [('scripts/assessment.py', 'verify_loss_likelihood'), ('src/probability.py', 'ProbabilityLoss.normal_pdf'), ('src/backprop.py', 'forward_backward')],
        'images': [], 'notebook': 'probability_loss.ipynb',
    },
]
